#!/usr/bin/env bash


mkdir provision
cd provision
wget https://raw.githubusercontent.com/eftakhairul/trusty64/master/provision/setup.sh
cd ..
wget https://raw.githubusercontent.com/eftakhairul/trusty64/master/Vagrantfile
vagrant up --provision
